name: test checkout

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'checkout'
        required: true
        default: 'main'

jobs:
  run-command:
    runs-on: [ubuntu-latest] 

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.command }}
